### ASSIGNMENT No: 5 

Title: To illustrate Artificial Neural Network training process in Python 

Problem Statement: Implement an Artificial Neural Network training process in Python by using Forward Propagation, and Back Propagation. 

In [1]:
# This cell contains ANN-related code
# Comments are added for understanding
import numpy as np  # Import libraries


In [2]:
# This cell contains ANN-related code
# Comments are added for understanding
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)

In [3]:
# This cell contains ANN-related code
# Comments are added for understanding
X = np.array([  # Assign value
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([[0], [1], [1], [0]])  # Assign value


In [4]:
# This cell contains ANN-related code
# Comments are added for understanding
np.random.seed(42)

input_neurons = 2  # Assign value
hidden_neurons = 3  # Assign value
output_neurons = 1  # Assign value

W1 = np.random.uniform(size=(input_neurons, hidden_neurons))  # Assign value
b1 = np.random.uniform(size=(1, hidden_neurons))  # Assign value

W2 = np.random.uniform(size=(hidden_neurons, output_neurons))  # Assign value
b2 = np.random.uniform(size=(1, output_neurons))  # Assign value

learning_rate = 0.1  # Assign value
epochs = 10000  # Assign value


In [5]:
# This cell contains ANN-related code
# Comments are added for understanding
for epoch in range(epochs):
    
    # ---- Forward Propagation ---
    hidden_input = np.dot(X, W1) + b1  # Assign value
    hidden_output = sigmoid(hidden_input)  # Assign value
    
    final_input = np.dot(hidden_output, W2) + b2  # Assign value
    predicted_output = sigmoid(final_input)  # Predict output
    
    # ---- Error Calculation ---
    error = y - predicted_output  # Predict output
    
    # ---- Backpropagation ---
    d_output = error * sigmoid_derivative(predicted_output)  # Predict output
    
    error_hidden = d_output.dot(W2.T)  # Assign value
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)  # Assign value
    
    # ---- Update Weights ---
    W2 += hidden_output.T.dot(d_output) * learning_rate  # Assign value
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate  # Assign value
    
    W1 += X.T.dot(d_hidden) * learning_rate  # Assign value
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate  # Assign value


In [6]:
# This cell contains ANN-related code
# Comments are added for understanding
print("\nFinal Predicted Output:")
predicted_output  # Predict output



Final Predicted Output:


array([[0.05009215],
       [0.92079488],
       [0.90354216],
       [0.10615431]])

In [7]:
# This cell contains ANN-related code
# Comments are added for understanding
print("\nRounded Predictions (0 or 1):")
np.round(predicted_output).astype(int)  # Predict output



Rounded Predictions (0 or 1):


array([[0],
       [1],
       [1],
       [0]])

In [8]:
# This cell contains ANN-related code
# Comments are added for understanding
print("\nExpected Output:")
y


Expected Output:


array([[0],
       [1],
       [1],
       [0]])