### ASSIGNMENT No: 09 

Title: Write a python program to design a Hopfield Network which stores 4 vectors  

Problem Statement:  Design a Hopfield Network which stores 4 vectors  

In [1]:
# This cell contains ANN-related code
# Comments are added for understanding
import numpy as np  # Import libraries


In [2]:
# This cell contains ANN-related code
# Comments are added for understanding
patterns = np.array([  # Assign value
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [1, 1, -1, -1],
    [-1, -1, 1, 1]
])

In [3]:
# This cell contains ANN-related code
# Comments are added for understanding
class HopfieldNetwork:
    
    def __init__(self):
        self.W = None   # weight matrix  # Assign value

    # 🔹 Train using Hebbian Learning
    def train(self, patterns):
        n = patterns.shape[1]  # Assign value
        self.W = np.zeros((n, n))  # Assign value
        
        for p in patterns:
            p = p.reshape(n, 1)  # Assign value
            self.W += p @ p.T   # outer product  # Assign value
        
        # remove self connections
        np.fill_diagonal(self.W, 0)

    # 🔹 Recall function
    def recall(self, x, steps=5):  # Assign value
        x = x.copy()  # Assign value
        
        for _ in range(steps):
            x = np.sign(self.W @ x)  # Assign value
        
        return x

In [4]:
# This cell contains ANN-related code
# Comments are added for understanding
model = HopfieldNetwork()  # Assign value
model.train(patterns)

print("Weight Matrix:\n", model.W)

Weight Matrix:
 [[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]


In [5]:
# This cell contains ANN-related code
# Comments are added for understanding
# slightly corrupted pattern
test = np.array([1, -1, 1, -1])  # Assign value

print("Input:", test)
print("\n")

output = model.recall(test)  # Assign value

print("Recovered Output:", output)

Input: [ 1 -1  1 -1]


Recovered Output: [ 1. -1.  1. -1.]
